[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
flexfi_program = "GZYx7tr7vmLp92WgCfyaPmP68zm15RdSiCt31D9fUDoV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/mickaelsanchesloureiro/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
